/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define TIM2_IRQ_NO		28
#define I2C1_IRQ_NO		31


void config_priority(uint8_t IRQ_num, uint8_t priority);

int main(void)

{
	//1. priority config using nvic ipr registers
	uint8_t timer_priority=0x80;
	uint8_t i2c_priority=0x70;

	config_priority((uint8_t) TIM2_IRQ_NO, timer_priority);
	config_priority((uint8_t) I2C1_IRQ_NO, i2c_priority);

	//2. interrupt pending
	uint32_t *ISPR= (uint32_t *)0XE000E200U;
	uint8_t reg1_select = TIM2_IRQ_NO	/32;
	uint8_t pos1_select= (TIM2_IRQ_NO	 % 32);
	ISPR[reg1_select] |= (0x1<<pos1_select);

	uint8_t reg2_select = I2C1_IRQ_NO	/32;
	uint8_t pos2_select= (I2C1_IRQ_NO	 % 32);
	ISPR[reg2_select] |= (0x1<<pos2_select);

	//3. interrupt enable
	uint32_t *ISER= (uint32_t *)0XE000E100U;
	uint8_t reg3_select = TIM2_IRQ_NO	/32;
	uint8_t pos3_select= (TIM2_IRQ_NO % 32);
	ISER[reg3_select] |= (0x1<<pos3_select);

}

void config_priority(uint8_t IRQ_num, uint8_t priority)
{
	uint32_t * IPR = (uint32_t *)0xE000E400U; // first address

	uint8_t reg_select = IRQ_num/4;
	uint8_t pos_select= (IRQ_num % 4)*8;

	IPR[reg_select] &= ~(0xFF<<pos_select);
	IPR[reg_select] |= (priority<<pos_select);



}

void TIM2_IRQHandler(void)

{
	printf("inside TIM2 IRQ Handler");
	uint32_t *ISER= (uint32_t *)0XE000E100U;
	uint8_t reg_select = I2C1_IRQ_NO	/32;
	uint8_t pos_select= (I2C1_IRQ_NO % 32);
	ISER[reg_select] |= (0x1<<pos_select);
	while(1);

}

void I2C1_EV_IRQHandler(void)

{
	printf("Inside I2C IRQ HANDLER");
}

